---
title: "Aides Drug"
author: "Karen Gomez"
date: "Summer 2023"
output: html_document
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
triUmp <-read.csv(file="triUmpsal.csv",header=TRUE)
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?.  If you skimp in this section expect to be marked down in your grade. Paint a picture of the project a couple of paragraphs is expected!-->

A new  preventative aides drug (triUmpsal) is under test in clinical trials. Consider only the DrugUsers, does this drug seem effective?  Hint - use dplyr to obtain that subpopulation with the filter command.

$H_0$: The vaccine (drug) is not effective in preventing aids among drug users.  
$H_A$: The vaccine (drug) is effective in preventing aids among drug users.  
Data for this study came from a clinical trial for the drug triUmpsal. 

# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method. Discuss what data manipulations may be needed for example subsetting or other binning procedures and what sort of graphical displays and inferential tools will be used!-->

Because the question is about drug users, we have to subset the data to include only druggies. The response variable for the drug triUmpsal is Categorical; the input variable is Categorical. We have a CAT~CAT.

Graphical display: bar chart, numerical display is detail version of the graphical using specific numbers while the inferential way is finding the ratio or difference between the different methods we used, so in case it is the TriUmpsal drug users and non-TriUmpsal drug users effects of contracting AIDS.

# Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question. Bottom line is to explain the features of the graph that are relevant to conforming or departing to what is expected by your null hypothesis !-->

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
